openapi: 3.0.0
info:
  contact: {}
  title: My API
  version: "1.0"
paths:
  "/users/{id}":
    get:
      description: Get a single user by its ID
      parameters:
        - description: User ID
          in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/main.User"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                type: string
      summary: Get specific User By ID
      tags:
        - users
  /users/CreateUser:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/main.User"
        description: Create User
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/main.User"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: string
      summary: Create New User
      tags:
        - users
  "/users/Delete/{id}":
    delete:
      parameters:
        - description: User ID
          in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: User Deleted
          content:
            application/json:
              schema:
                type: string
        "404":
          description: User not found
          content:
            application/json:
              schema:
                type: string
      summary: Delete New User
      tags:
        - users
  /users/GetAllUsers:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/main.User"
                type: array
      summary: Get all Users
      tags:
        - users
  "/users/Update/{id}":
    put:
      parameters:
        - description: User ID
          in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/main.User"
        description: Update User
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/main.User"
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: string
        "404":
          description: User not found
          content:
            application/json:
              schema:
                type: string
      summary: Update New User
servers:
  - url: http://localhost:8080
components:
  schemas:
    main.User:
      properties:
        ID:
          type: integer
        name:
          type: string
      type: object
